# Generated by Django 5.2.6 on 2025-11-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twitter", "0002_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=models.TextField(max_length=300),
        ),
    ]
